# Hemmeligheder til Postgres + app-forbindelse (base64: proxi/proxi/proxi)
apiVersion: v1
kind: Secret
metadata:
  name: proxi-db
  namespace: proxi
type: Opaque
stringData:
  POSTGRES_USER: proxi
  POSTGRES_PASSWORD: proxi
  POSTGRES_DB: proxi
  NODE_DB_USER: proxi
  NODE_DB_PASSWORD: proxi
  NODE_DB_NAME: proxi
