# K3s bruger Traefik – Ingress eksponerer appen på http
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proxi-app
  namespace: proxi
  annotations:
    # Traefik (K3s default) – valgfrit
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: proxi-app
                port:
                  number: 80
